# Generated by Django 3.0.5 on 2020-10-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField()),
                ('coins', models.IntegerField()),
                ('icon', models.ImageField(upload_to='')),
                ('rating', models.FloatField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
