# Generated by Django 3.0.5 on 2020-10-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeHelpServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UID',
        ),
    ]
