# Generated by Django 3.0.5 on 2020-12-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeHelpServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='activate',
            new_name='active',
        ),
    ]
