# Generated by Django 3.0.5 on 2020-10-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeHelpServer', '0002_remove_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
