# Generated by Django 3.0.5 on 2020-12-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeHelpServer', '0002_auto_20201201_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accept_task', to='WeHelpServer.User'),
        ),
    ]
