# Generated by Django 3.0.5 on 2020-11-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeHelpServer', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chatList',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(max_length=4096),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeHelpServer.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_list', models.CharField(max_length=4096)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_a', to='WeHelpServer.User')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_b', to='WeHelpServer.User')),
                ('last_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeHelpServer.Message')),
            ],
        ),
    ]
