# Generated by Django 3.0.5 on 2020-12-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeHelpServer', '0004_auto_20201203_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acceptor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accept_task', to='WeHelpServer.User'),
        ),
    ]
