# Generated by Django 3.0.5 on 2020-12-01 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeHelpServer', '0005_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message_list',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='WeHelpServer.Chat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_freecoin',
            field=models.DateTimeField(default=models.DateTimeField()),
        ),
        migrations.AddField(
            model_name='user',
            name='num_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_chat', to='WeHelpServer.Message'),
        ),
    ]
