import React, { useState, useCallback, useContext } from 'react';
import { View, Text, Alert, ScrollView, RefreshControl } from 'react-native';
import { ListItem, Avatar } from 'react-native-elements';
import { PageHeader } from '../components/PageHeader';
import { createStackNavigator } from '@react-navigation/stack';
import { ChatPage } from './ChatPage'
import { UserContext } from '../components/UserContext';
import { UserDetailPage } from './UserDetailPage';

let Stack = createStackNavigator();

/**
 *
 * MessagePage has a child componet ChatList which is one of the observer under the subject App.js.
 * It will be notified if there are new message from other users.
 * As soon as the variable chatList changed in App.js, MessagePage will rerender and update the new message for the corresponding ChatBox.
 * MessagePage also has basic navigation logic to jump between different ChatPage.
 * 
 * @export
 * @param {none}
 * @return {Component} => Render a MessagPage component with navigation logic
 */
export function MessagePage() {
  return (
    <Stack.Navigator headerMode='false'> 
      <Stack.Screen name='Contacts' component={ChatList}/>
      <Stack.Screen name='ChatPage' component={ChatPage}/>
      <Stack.Screen name='UserDetailPage' component={UserDetailPage}/>
    </Stack.Navigator>
  );
}

/**
 *
 * ChatList is an observer and a child component of MessagePage that will render a list of previous contacted user.
 *
 * @param {{navigation: Object}} props props.navigation is generated by the stack navigator in React-Navigation used to redirect to other pages.
 * @return {Component} => Render a ChatList component where each item of the list is a contact and is clickable and redirect to the ChatBox.
 */
function ChatList(props) {

  //const removeChat = useCallback((index) => {
  //  Alert.alert('Delete this chat',
  //  '',
  //  [
  //    {
  //      text: 'Delete',
  //      onPress: () => {
  //        setContacts((prevContact) => {
  //          prevContact.splice(index, 1);
  //          return [...prevContact];
  //        })
  //      }
  //    },
  //    { text: 'Cancel',
  //      style: 'cancel'
  //    },
  //  ],
  //  { cancelable: true })
  //})



  const [user, chatList] = useContext(UserContext);
  const [refreshing, setRefreshing] = React.useState(false);

  const wait = useCallback((timeout) => {
    return new Promise(resolve => {
      setTimeout(resolve, timeout);
    });
  }, []);

  const onRefresh = useCallback(() => {
    setRefreshing(true);

    wait(2000).then(() => setRefreshing(false));
  }, []);
  
  return (
    <View style={{flex: 1, justifyContent: 'flex-start', backgroundColor: 'white'}}>
      <PageHeader centerComp={<Text style={{fontSize: 18, fontWeight: "bold"}}>Message</Text>} />
      <ScrollView
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
        }
      >
      {
        chatList.map((chat, i) => (
          <ListItem key={i} bottomDivider 
          onPress={() => {
            props.navigation.navigate('ChatPage', {chat: chat});
          }}
          //onLongPress={()=> {removeContact(i);}}
          >
            <Avatar source={{uri: chat.avatar}} 
                    onPress={() => {props.navigation.navigate('UserDetailPage', {userUID: 8})}}/>
            <ListItem.Content>
              <ListItem.Title>{chat.name}</ListItem.Title>
              <ListItem.Subtitle>{chat.comment}</ListItem.Subtitle>
            </ListItem.Content>
          </ListItem>
        ))
      }
      </ScrollView> 
    </View>
  );
}