import React, { useContext, useCallback } from 'react';
import Constants from 'expo-constants';
import { View, Text, ScrollView, StyleSheet, RefreshControl } from 'react-native';
import { AppleCard } from 'react-native-apple-card-views'
import { createStackNavigator } from '@react-navigation/stack';
import { TaskDetailPage } from './TaskDetailPage';
import { UserDetailPage } from './UserDetailPage';
import { ChatPage } from './ChatPage';
import { EventRegister } from 'react-native-event-listeners';
import { UserContext } from '../components/UserContext';

const Stack = createStackNavigator();

/**
 *
 * TaskPage contains the basic navigation logic to jump between differnt taskDetailPage and chatPage.
 *
 * @export
 * @param {none}
 * @return {Component} => Render a TaskPage with navigation logic
 */
export function TaskPage() {
    return (
        <Stack.Navigator headerMode='false'> 
            <Stack.Screen name='TaskMainPage' component={TaskMainPage}/>
            <Stack.Screen name='TaskDetailPage' component={TaskDetailPage}/>
            <Stack.Screen name='UserDetailPage' component={UserDetailPage}/>
            <Stack.Screen name='ChatPage' component={ChatPage}/>
        </Stack.Navigator>
    );
}

/**
 *
 * TaskMainPage is an observer under the subject of App.js. It contains a list of cards of tasks.
 * As soon as taskList changed in App.js, the TaskMainPage will rerender its card of the tasks.
 *
 * @param {{navigation: Object}} props props.navigation is generated by the stack navigator in React-Navigation used to redirect to other pages.
 * @return {Component} => Render a TaskMainPage with ScrollView consisting of cards of tasks.
 */
function TaskMainPage(props) {
    const [user, chatList, taskList] = useContext(UserContext);
    const [refreshing, setRefreshing] = React.useState(false);

    const wait = useCallback((timeout) => {
        return new Promise(resolve => {
          setTimeout(resolve, timeout);
        });
    }, []);

    const onRefresh = useCallback(() => {
        EventRegister.emit('refreshTaskList');
        setRefreshing(true);
        wait(2000).then(() => setRefreshing(false));
    }, []);

    return (
        <View style={{flex: 1, justifyContent: 'space-between', backgroundColor: 'white'}}>
            <View style={{flex: 8, top:Constants.statusBarHeight}}>
                <ScrollView 
                    contentContainerStyle={{paddingBottom:Constants.statusBarHeight}}
                    refreshControl={
                        <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
                    }
                >
                    <Text style={{fontSize:25, padding: 10, top:10}}>Accepted Tasks</Text>
                    {taskList.map((t, i) => {
                        if(t.receiverUID == user.UID) {
                            return (<TaskCard task={t} key={i} navigation={props.navigation}/>);
                        }
                    })}
                    <Text style={{fontSize:25, padding: 10, top:10}}>Published Tasks</Text>
                    {taskList.map((t, i) => {
                        if(t.publisherUID == user.UID) {
                            return (<TaskCard task={t} key={i} navigation={props.navigation}/>);
                        }
                    })}
                </ScrollView>
            </View>
        </View>
    );
}

/**
 *
 * TaskCard will render the task information based on the task object passed by HomeMainPage similar to CardField but with different styles.
 *
 * @param {{task: Object, navigation: Object}} props Object contains two key-value pair:<br>
 *  1. props.task:
 *     {
 *          publisher: String,
 *          publisherUID: number,
 *          receiverUID: number,
 *          taskID: number,
 *          avatar: string,
 *          rating: number,
 *          coins: number,
 *          cost: number,
 *          datetime: datetime,
 *          title: string,
 *          description: string,
 *          img: string[],
 *     }
 * 2. props.navigation is generated by the stack navigator in React-Navigation used to redirect to other pages.
 * @return {Component} => Render a TaskCard that is correspoinding to one task.
 */
function TaskCard(props) {
    return(
        <AppleCard
            style={styles.containerStyle}
            smallTitle={props.task.publisher}
            largeTitle={props.task.title}
            footnoteText={''}
            largeTitleTextStyle={styles.largeTitleTextStyle}
            smallTitleTextStyle={styles.smallTitleTextStyle}
            // footnoteTextStyle={styles.footnoteTextStyle}
            source={{uri: props.task.avatar}}
            backgroundStyle={styles.backgroundStyle}
            onPress={() => {props.navigation.navigate('TaskDetailPage', {task:props.task});}}
        />
    )
}

const styles = StyleSheet.create({
    containerStyle: {
        padding: 5,
        width: '100%'
    },
    largeTitleTextStyle: {
        fontSize: 35,
        color: 'black'
    },
    smallTitleTextStyle: {
        fontSize: 15,
        color: 'black'
    },
    footnoteTextStyle: {
        fontSize: 24,
        color: 'black',
        backgroundColor: '#D5DBDB7F'
    },
    backgroundStyle: {
        width: '100%',
        height: 350
    }
})