import React, { useState, useEffect, useCallback, useContext, Component } from 'react';
import { View, Keyboard } from 'react-native';
import { GiftedChat, Avatar, Bubble, Time } from 'react-native-gifted-chat';
import { LinearGradient } from 'expo-linear-gradient';
import { UserContext } from './UserContext';
import { EventRegister } from 'react-native-event-listeners';

/**
 *
 * ChatBox imports react-native-gifted-chat. 
 * It will rerender and update new messages as soon as chatList in App.js updates and chatPage is notified.
 * It then passes an array of messages to gifted chat. Gifted chat will generate an interactive chat window.
 *
 * @export
 * @param {{chat: Object, navigation:object}} props <br>
 * 1. props.chat is a chat object and one element of chatList in App.js.
 *  props.chat =  {
 *           'updating': boolean
 *           'chatID': number
 *           'avatar': string
 *           'name': string, the other user's name
 *           'UID': number, the other user's UID
 *           'comment': string, last_message
 *           'datetime': datetime of last_message, format in %Y-%m-%d %H:%M:%S
 *           'messages': [{'UID', 'message'}*], sorted
 *          }
 * 2. props.navigation is generated by the stack navigator in React-Navigation used to redirect to other pages.
 * @return {Component} => Render a ChatBox Component
 */
export function ChatBox(props) {
    const [user, chatList] = useContext(UserContext);
    const chat = props.chat;

    //change this to event trigger to update chat and send post request to server
    const onSend = useCallback((newMessage = []) => 
      {EventRegister.emit('sendMessage', [newMessage, chat['UID']])}, []);

    return (  
      <GiftedChat
        messages={chat['messages']}
        onSend={newMessage => {
          Keyboard.dismiss();
          onSend(newMessage)}}
        alwaysShowSend={true}
        renderAvatar={renderAvatar}
        renderBubble={renderBubble}
        renderTime={renderTime}
        multiline={true}
        isLoadingEarlier={true}
        onPressAvatar={() => {props.navigation.navigate('UserDetailPage', {userUID: chat['UID']})}}
        user = {{
            _id: user.UID,
            name: user.name,
            avatar: user.photoUrl
        }}
      />
    );
  }

function renderAvatar(props) {
    return(
      <Avatar
        {...props}
        imageStyle={{
            left:{
              bottom:5,
              borderBottomLeftRadius: 5,
              borderBottomRightRadius: 5,
              borderTopLeftRadius: 5,
              borderTopRightRadius: 5
            },
            right:{
              bottom:5,
              borderBottomLeftRadius: 5,
              borderBottomRightRadius: 5,
              borderTopLeftRadius: 5,
              borderTopRightRadius: 5
            }
        }}
      />
    );
  }
  
function renderBubble(props) {
    return (
      <View 
      style={{
          borderBottomLeftRadius: 15,
          borderBottomRightRadius: 15,
          borderTopLeftRadius: 15,
          borderTopRightRadius: 15,
          overflow: 'hidden',
          }}>
        <LinearGradient
          colors={['#5099E1', '#27DAF0']}
          style={{
            position: 'absolute',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
          }}
        />
        <Bubble
            {...props}
            wrapperStyle={{
              right: {
                backgroundColor: 'transparent',
                marginLeft: 0
              },
              left: {
                backgroundColor: 'transparent',
                marginRight: 0,
              }
            }}
            textStyle={{
              right: {
                color: 'white'
              },
              left: {
                color: 'white'
              }
            }}
          />
        </View>
    );
}
  
function renderTime(props) {
    return (
      <Time 
        {...props}
        timeTextStyle= {{
          left: {
            color: '#fff'
          },
          right: {
            color: '#fff'
          }
        }}
      />
    );
}